import fs from 'node:fs';
const files={water:'rushing-water.wav',grass:'grasshopper.mp3',nature:'night-nature.mp3',market:'market-india.mp3'};
const assets={};for(const [key,file] of Object.entries(files))assets[key]='data:audio/'+(file.endsWith('.wav')?'wav':'mpeg')+';base64,'+fs.readFileSync('assets/audio/'+file).toString('base64');
assets.scream=fs.existsSync('assets/audio/jump-scream.wav')?'data:audio/wav;base64,'+fs.readFileSync('assets/audio/jump-scream.wav').toString('base64'):null;
fs.writeFileSync('audio-assets.js','/* Generated by build-audio.mjs; licenses in assets/audio/README.md. */\nwindow.DreamSoundAssets='+JSON.stringify(assets)+';\n');
console.log('Packaged ambience audio; scream '+(assets.scream?'present':'awaiting a file with an audio track')+'.');
