import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

// A classic-script build with packaged assets also works when index.html is
// opened directly. No module fetch, model fetch or separate preview is needed.
const root=path.dirname(fileURLToPath(import.meta.url));
const read=name=>fs.readFileSync(path.join(root,name),'utf8');
function dataURL(name,mime){return `data:${mime};base64,${fs.readFileSync(path.join(root,name)).toString('base64')}`;}
function imports(source){
 return source.replace(/import\s*\{([\s\S]*?)\}\s*from\s*['"]([^'"]+)['"];?/g,(_,names,file)=>{
  const dependency=file.includes('BufferGeometryUtils')?'geometryUtils':'THREE';
  const bindings=names.split(',').map(x=>x.trim()).filter(Boolean).map(x=>x.replace(/\s+as\s+/,':')).join(',');
  return `const {${bindings}}=${dependency};`;
 });
}
function moduleBody(file){
 const source=imports(read(file));
 const exported=source.match(/export\s*\{([^}]+)\};?\s*$/);
 if(!exported)throw Error('Unsupported module exports: '+file);
 const standalone=[...source.matchAll(/^\s*export\s+(?:function|const|class)\s+(\w+)/gm)].map(match=>match[1]);
 const bindings=exported[1].split(',').concat(standalone).map(x=>x.trim()).filter(Boolean).map(x=>{
  const [local,alias]=x.split(/\s+as\s+/);return alias?`${alias}:${local}`:local;
 }).join(',');
 const body=source.slice(0,exported.index).replace(/^export\s+(?=function|const|class)/gm,'');
 return `(()=>{\n${body}\nreturn {${bindings}};\n})()`;
}
const tree=JSON.parse(read('assets/rural/tree/tree-web.gltf'));
for(const buffer of tree.buffers)buffer.uri=dataURL('assets/rural/tree/'+buffer.uri,'application/octet-stream');
for(const image of tree.images)image.uri=dataURL('assets/rural/tree/'+image.uri,image.mimeType||'image/jpeg');
const assets={
 jumpScare:dataURL('assets/rural/jump-scare-clear.png','image/png'),
 groundColor:dataURL('assets/rural/ground-color.jpg','image/jpeg'),
 groundNormal:dataURL('assets/rural/ground-normal.jpg','image/jpeg'),
 treeJSON:JSON.stringify(tree),
};
const streetAssets={people:{}};
for(const name of ['sam','maya','jordan'])streetAssets.people[name]=dataURL('assets/street/'+name+'-web.glb','model/gltf-binary');
for(const material of ['asphalt','plaster'])for(const map of ['Color','Normal','Rough'])streetAssets[material+map]=dataURL('assets/street/'+material+'-'+map.toLowerCase()+'.jpg','image/jpeg');
let visual=read('visual2.js').replace(/^import[^\n]+\n/gm,'').replace(/^export\s+(?=function|const|class)/gm,'');
const street=read('visual3.js').replace(/^import[^\n]+\n/gm,'').replace(/^export\s+(?=function|const|class)/gm,'');
if(/^\s*(import|export)\s/m.test(visual))throw Error('Unhandled module declaration');
const bundle=`/* Generated by build-visual2.mjs. Poly Haven assets: CC0 (https://polyhaven.com/license).
${read('vendor/THREE-LICENSE.txt')}
*/
(()=>{'use strict';
const THREE=${moduleBody('vendor/three.module.js')};
const geometryUtils=${moduleBody('vendor/BufferGeometryUtils.js')};
const {GLTFLoader}=${moduleBody('vendor/GLTFLoader.js')};
const skeletonUtils=${moduleBody('vendor/SkeletonUtils.js')};
const cloneSkeleton=skeletonUtils.clone,mergeGeometries=geometryUtils.mergeGeometries;
let packagedAssets=${JSON.stringify(assets)};
let packagedStreetAssets=${JSON.stringify(streetAssets)};
${visual}
${street}
window.RuralVisual={createRuralScene(){
 const assets=packagedAssets;packagedAssets=null;
 return createRuralScene({assets});
},createStreetScene(rural){
 const assets=packagedStreetAssets;packagedStreetAssets=null;
 return createStreetScene({rural,assets});
}};
})();
`;
// Parse the generated script before publishing it to the output path.
new Function(bundle);
fs.writeFileSync(path.join(root,'visual2.bundle.js'),bundle);
console.log(`Built visual2.bundle.js (${(Buffer.byteLength(bundle)/1024/1024).toFixed(1)} MB), including all landscape assets.`);
